export const TASK_TEXT = 'TASK_TEXT';
export const LOAD_TASK = 'LOAD_TASK';
export const CREATE_TASK = 'CREATE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const FILTER_TASK = 'FILTER_TASK';
// export const FILTER_STATUS = 'TASK_FILTER_STATUS';

export const DELETE_TASK = 'DELETE_TASK';
export const TASK_COMPLETED = "TASK_COMPLETED";
export const TASK_DELETE_ALL = 'TASK_DELETE_ALL';
export const TASK_UPDATE_CHECK = 'TASK_UPDATE_CHECK';
export const TASK_COMPLETED_ALL = 'TASK_COMPLETED_ALL';
